### PR TITLE
Update to fix param validations

### PR DESCRIPTION
**Pull request by pboysen**
Changed code to call validate on type, not param.  I also passed `dom` to validate so I can use browser validation.  The value can be retrieved from dom if needed.  I have converted my demo to use the new menu API and will release it early next week.  Nice reorganization.  Greatly simplified my code and it is very flexible.

### CODE REVIEW

**Comment by pboysen** [comment]
Minor spelling to public docs but confused me when I read it.

**Comment by marijnh** [comment]
As I mentioned in #192, I do want to keep supporting validation methods on individual params. Could you revise your branch to leave in the original code as well? (Also, try not to include merge commits and irrelevant things like 881f523 in pull requests)

**Comment by pboysen** [comment]
Ok, I will close this and issue a new one.

**Comment by marijnh** [comment]
(You can force-push to pull request branches to update the code in them.)

**Pull request closed without merging**
