### PR TITLE
Create .babelrc

### LINKED ISSUE #65: error occur when use webpack to package the project
Hash: a7e67fc458a9cba10338
Version: webpack 1.12.2
Time: 18050ms
    Asset    Size  Chunks             Chunk Names
bundle.js  226 kB       0  [emitted]  main
    + 50 hidden modules

ERROR in ./src/edit/commands.js
Module build failed: Error: C:/Users/zhou/Desktop/prosemirror/src/edit/commands.js: We found a path that isn't a NodePath instance
    at Function.get (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\path\index.js:103:13)
    at TraversalContext.create (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\context.js:73:30)
    at TraversalContext.visitMultiple (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\context.js:102:25)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\context.js:193:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\index.js:139:17)
    at traverse (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\index.js:61:12)
    at Function.traverse.hasType (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\index.js:188:3)
    at BlockScoping.wrapClosure (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:491:47)
    at BlockScoping.run (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:383:12)
    at PluginPass.Loop (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:89:36)
    at newFn (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\visitors.js:233:27)
    at NodePath._call (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:72:18)
    at NodePath.call (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:44:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:102:12)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitMultiple (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:106:17)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:193:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:139:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:106:22)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitSingle (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:111:19)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:195:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:139:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:106:22)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitMultiple (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:106:17)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:193:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:139:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:106:22)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
 @ ./src/edit/index.js 61:16-37

ERROR in ./src/edit/input.js
Module build failed: Error: C:/Users/zhou/Desktop/prosemirror/src/edit/input.js: We found a path that isn't a NodePath instance
    at Function.get (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\path\index.js:103:13)
    at TraversalContext.create (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\context.js:73:30)
    at TraversalContext.visitMultiple (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\context.js:102:25)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\context.js:193:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\index.js:139:17)
    at traverse (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\index.js:61:12)
    at Function.traverse.hasType (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\index.js:188:3)
    at BlockScoping.wrapClosure (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:491:47)
    at BlockScoping.run (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:383:12)
    at PluginPass.Loop (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:89:36)
    at newFn (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\visitors.js:233:27)
    at NodePath._call (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:72:18)
    at NodePath.call (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:44:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:102:12)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitMultiple (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:106:17)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:193:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:139:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:106:22)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitSingle (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:111:19)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:195:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:139:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:106:22)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitMultiple (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:106:17)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:193:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:139:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:106:22)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
 @ ./src/edit/main.js 32:13-31

ERROR in ./src/transform/ancestor.js
Module build failed: Error: C:/Users/zhou/Desktop/prosemirror/src/transform/ancestor.js: We found a path that isn't a NodePath instance
    at Function.get (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\path\index.js:103:13)
    at TraversalContext.create (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\context.js:73:30)
    at TraversalContext.visitMultiple (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\context.js:102:25)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\context.js:193:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\index.js:139:17)
    at traverse (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\index.js:61:12)
    at Function.traverse.hasType (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\index.js:188:3)
    at BlockScoping.wrapClosure (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:491:47)
    at BlockScoping.run (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:383:12)
    at PluginPass.Loop (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:89:36)
    at newFn (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\visitors.js:233:27)
    at NodePath._call (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:72:18)
    at NodePath.call (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:44:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:102:12)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitMultiple (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:106:17)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:193:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:139:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:106:22)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitSingle (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:111:19)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:195:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:139:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:106:22)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitMultiple (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:106:17)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:193:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:139:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:106:22)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
 @ ./src/transform/index.js 32:16-37

ERROR in ./src/transform/replace.js
Module build failed: Error: C:/Users/zhou/Desktop/prosemirror/src/transform/replace.js: We found a path that isn't a NodePath instance
    at Function.get (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\path\index.js:103:13)
    at TraversalContext.create (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\context.js:73:30)
    at TraversalContext.visitMultiple (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\context.js:102:25)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\context.js:193:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\index.js:139:17)
    at traverse (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\index.js:61:12)
    at Function.traverse.hasType (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\index.js:188:3)
    at BlockScoping.wrapClosure (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:491:47)
    at BlockScoping.run (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:383:12)
    at PluginPass.BlockStatementProgram (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:96:24)
    at newFn (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\visitors.js:233:27)
    at NodePath._call (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:72:18)
    at NodePath.call (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:44:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:102:12)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitSingle (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:111:19)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:195:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:139:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:106:22)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitMultiple (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:106:17)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:193:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:139:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:106:22)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitSingle (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:111:19)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:195:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:139:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:106:22)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
 @ ./src/transform/index.js 93:0-20

### PR DESCRIPTION
**Pull request by forresto**
This allows people building prosemirror from node_modules with webpack and babel 6.

fixes #65

more discussion: https://discuss.prosemirror.net/t/webpack-es6-import-issue/59/2

### CODE REVIEW

**Comment by marijnh** [comment]
Is this something that people are using? My understanding is that the proper way to handle this is to distribute the library as a set of pre-compiled files (which is why there's a `dist` directory).

I mean, if you have a big dependency tree, rebuilding all of that every time you bundle your system is just not going to be workable, right?

**Comment by forresto** [comment]
I'm don't know if there is a standard practice settled out. I like to require prosemirror modules by their `src` paths instead of all `prosemirror/dist`. But it would be more of a pain if I was not using es6.

**Comment by arekkas** [comment]
If you want people to be able to just load specific parts of the library (like in lodash), this would be appropriate. If not, it doesn't really make sense to include stuff from the src directory.

**Comment by forresto** [comment]
Closing as this is Babel 6 specific. #117

**Pull request closed without merging**
