### PR TITLE
fix coordsAtPos at softlinebreak and after last character within block element, fixes #322

### LINKED ISSUE #322: coordsAtPos giving incorrect values
In at least these two situations, the coordinates do not seem correct. The below have come up as issues while trying to find the coordinates of empty ranges.

1. After the last letter within a blocknode containing severel lines of text. The coordinates given make it appear as if the pos is as high as the entire block (crossing several lines), and as if it's to the right of the block element.

2. At soft linebreaks. There is an issue with browsers in general, that they don't differentiate between before and after the line break (we are dealing with that), so PM won't be able to deal with this entirely by itself. However, currently coordsAtPos given back values that make it appear as if it is spanning both lines in height. getClientRects() should give give two different rects, and it would be preferable if one would simply chose one rather than trying to combine both with getBoundingClientRect(). Or alternatively allow for some way to return more than one set of coordinates.

### PR DESCRIPTION
**Pull request by johanneswilm**
Please review. It is not clear to me if the textRect function is ever called with arguments that will give no clientRects at all. In that case adjustments need to be made. 

This places the rect at the start of the line at softline breaks. This is almost a random choice as line-end may have been just as valid. However, when moving the caret through the text using the arrow keys on Chrome, line start is preferred over line end. So if the case is to communicate the visual placement of the caret, in most cases line start will be preferable.

### CODE REVIEW

**Comment by johanneswilm** [comment]
I am wondering if the understanding of "after last letter in a blocknode" can have several meanings. For caret-sharing, it is clearly right after the letter. For other purposes it may be more approrpiate to look ath the end of the block itself, for example for user clicking somewhere in the last line of a paragraph beyond the last letter. Should the position of that place possibly be the entire remaining space in the last line?

**Comment by marijnh** [comment]
We don't have full control over the kind of DOM nodes that this needs to work on, so assuming that `getClientRects` returns at least one rectangle isn't a good idea. Sorry to have left this for so long, will try to properly study it tomorrow.

**Comment by marijnh** [comment]
So I'm not convinced that we need the extra flag. I've pushed b1a41e43a...314bef737 which simply makes looking at the nearest rectangle the default behavior. Let me know if you find a problem with this approach.

**Comment by johanneswilm** [comment]
@marijnh Yes, your changes seem to fix this. Thanks!

**Pull request closed without merging**
