### PR TITLE
Carry selection through undo and redo

### LINKED ISSUE #63: Do something intelligent with selection on undo/redo
We may want to reset to the selection that existed when the action was originally done. Right now it just maps the current selection to the updated document, which is solid, but not what users expect.

### PR DESCRIPTION
**Pull request by ericandrewlewis**
Fixes #63

### CODE REVIEW

**Comment by marijnh** [comment]
Looks good! Could you

 * add tests, preferably a bunch of them

 * figure out a way to make selections survive compression (I think you can just map the old selection through the current `this.remap`, but I'm not 100% sure -- write tests to see whether it does the right thing in at least a few situations)

 * The return type of `popEvent` really needs that `?` (note the `return null` near the top). Also, it should contain the new `selection` property.

**Comment by ericandrewlewis** [comment]
Will do!

> add tests, preferably a bunch of them

I figure I should put tests in `tests/browser/test-history.js`, but `npm run test` doesn't execute those tests in the `browser/` folder. How can I run these tests?

**Comment by marijnh** [comment]
> How can I run these tests?

Ah, you asked that somewhere before but I never got around to answering for some reason. The tests under `browser/` require a browser, and are run by opening `localhost:8080/test.html` in your browser (with moduleserve running and your `dist/` up to date).

**Comment by ericandrewlewis** [comment]
Marijn said:
> add tests, preferably a bunch of them

Totally. I [rewrote a flaky test](https://github.com/ericandrewlewis/prosemirror/commit/682502025ca7d0736a9f81dba7eb97a75b352800#diff-300311b4a2542f06630d0bb1058d6ba3R192) setting the editor's `historyEventDelay` to `-1`, which makes the test usable.

How would you suggest testing rebased selections? Should I use some of the fixtures from the collab module?

Marijn said:
> The return type of `popEvent` really needs that `?` (note the `return null` near the top). Also, it should contain the new `selection` property.

Ah yes, fixed up the docs appropriately.

**Comment by marijnh** [comment]
I've landed this as eb75727741faf2de and 0fdfac5148d9b8, and followed up with 235dbcf474fd688bf, which sanitizes the tests, creates a class for selection events, makes sure each event has a selection, and fixes some mapping issues. Let's open separate issues if we find further bugs related to this.

**Comment by Slapbox** [comment]
This doesn't seem to always work on Android. I wonder if there might be some oversight @marijnh?

Particularly when I backspace into a blockquote and then undo, the caret remains in the blockquote rather than reset to outside of it. I'm not sure if this is a generalizable bug but I've hit this in a few situations and it seems definite there are oversights in resetting the Android caret.

**Comment by Slapbox** [comment]
Actually it seems like the correct selection is not saved in the history to begin with in these cases. I don't know if that's because the selection has already moved by the time the value is being committed to the undo stack.

**Pull request closed without merging**
