### PR TITLE
Fix enter '<>' at the beginning of line

### PR DESCRIPTION
**Pull request by tzuhsiulin**

### CODE REVIEW

**Comment by marijnh** [comment]
That doesn't look right. `Node.copy` shouldn't be called with a string. If we have code that does so, that should be fixed. Could you elaborate on the actions that trigger the problem?

**Comment by tzuhsiulin** [comment]
When I typing a text addNode will be triggered, and It will using Node.copy combine left text and right text 
https://github.com/ProseMirror/prosemirror/blob/master/src/model/replace.js#L121

**Comment by marijnh** [comment]
Does attached patch help?

**Comment by tzuhsiulin** [comment]
yes, the patch fixes the issue. Thank you.

**Pull request closed without merging**
