### PR TITLE
fix an error about append children into closed node

### PR DESCRIPTION
**Pull request by tzuhsiulin**
When I pasted data like this, the test3, test4 and test5 will appended into closed node with test1. This will cause position error 
```
...
<div>
    <button><span>test1</span></button>
    <div>
        <div><h2 class="short">test2</h2></div>
        <div><span>test3 <span>test4</span> test5<br></span></div>
        <div></div>
    </div>
</div>
...
```

### CODE REVIEW

**Comment by marijnh** [comment]
The `<button>` tag isn't recognized at all by the parser, so there is no closed node for it to stop appending into. I don't think we should be making changes like this without having a good model of what _should_ happen. In the example code, I don't really see a reason why the behavior you're expecting is better than the current behavior.

**Comment by tzuhsiulin** [comment]
I'm sorry I gave a bad example

When I pasted html like this:
```
<div>
    <p>&nbsp;</p>
    <div>
        <div>
            <div>
                <button><span>test1</span></button>
                <div>
                    <div>
                        <h2>test2</h2>
                    </div>
                    <div>test3</div>
                </div>
            </div>
        </div>
    </div>
</div>
```
and the slice will be like this:
```
{
    "content": [
        {
            "type": "paragraph",
            "attrs": {
                "class": "",
                "align": "left"
            }
        },
        {
            "type": "paragraph",
            "attrs": {
                "class": "",
                "align": "left"
            },
            "content": [
                {
                    "type": "text",
                    "text": "test1"
                },
                {
                    "type": "text",
                    "text": "test3"
                }
            ]
        },
        {
            "type": "heading",
            "attrs": {
                "level": 2,
                "class": ""
            },
            "content": [
                {
                    "type": "text",
                    "text": "test2"
                }
            ]
        }
    ],
    "openLeft": 0,
    "openRight": 1
}
```
Now you can see the test3 has appended into closed node with test1, but it should be like this:
```
{
    "content": [
        {
            "type": "paragraph",
            "attrs": {
                "class": "",
                "align": "left"
            }
        },
        {
            "type": "paragraph",
            "attrs": {
                "class": "",
                "align": "left"
            },
            "content": [
                {
                    "type": "text",
                    "text": "test1"
                }
            ]
        },
        {
            "type": "heading",
            "attrs": {
                "level": 2,
                "class": ""
            },
            "content": [
                {
                    "type": "text",
                    "text": "test2"
                }
            ]
        },
        {
            "type": "paragraph",
            "attrs": {
                "class": "",
                "align": "left"
            },
            "content": [
                {
                    "type": "text",
                    "text": "test3"
                }
            ]
        }
    ],
    "openLeft": 0,
    "openRight": 1
}
```

**Comment by marijnh** [comment]
What does 'closed node' mean in this context?

**Comment by tzuhsiulin** [comment]
That mean is when the ```NodeBuilder.add``` has been trigger that will finished previous child and create a fragment append to ```NodeBuilder.content```.  But ```NodeBuilder.findPlace``` still find the 'closed node' to append a new node.

**Pull request closed without merging**
