### PR TITLE
Allow ProseMirror to load when window is undefined

### PR DESCRIPTION
**Pull request by salzhrani**
check for `window` before calling

### CODE REVIEW

**Comment by salzhrani** [comment]
I ran into this when loading the library server side

**Comment by marijnh** [comment]
Why are you loading the library server side? The model and transform modules can be loaded server side, as can the parser and serializer modules. But the core editor relies on a browser environment _all over_, so I don't think you'll get anything from loading it outside of one.

**Comment by salzhrani** [comment]
It is just for server side rendering ... I don't actually instantiate prosemirror server side... only on user interaction.

**Comment by marijnh** [comment]
But if you aren't using it, then why are you loading it?

**Comment by salzhrani** [comment]
I guess I can work around that.

**Pull request closed without merging**
