### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by adrianheine**
Pick them as you like.

### CODE REVIEW

**Comment by marijnh** [comment]
The change to `Node.some` would break code that uses its node-finding feature, so I've pushed 9c7e0d0  to change its doc comment instead.

Is explicitly converting something to string before concatenating it to a string needed for your typing work? I think I'm relying on implicit conversion in that case in a few other situations, so for now I've held off on merging fb910c6 . But if this is a special case for some reason, I would be okay with merging it.

The others have all been applied as 9c7e0d014200...0a874d8d1a0555

**Comment by adrianheine** [comment]
You probably meant 688d6d8ff33c89d9bd13d66f3821868493b85cd0, right? I didn't find any usage of `Node.some`s return value, but maybe I overlooked it. Your change works, too, though. Flow cannot handle implicit `toString` calls, but I tend to consider that a Flow bug; you shouldn't do that.

**Comment by marijnh** [comment]
> You probably meant 688d6d8, right?

Right.

So is this one instance of a missing `toString` call the only one in the codebase that Flow choked on, or merely the only one that you ran into so far?

**Comment by adrianheine** [comment]
No, it chokes on all of them. I think I just found another one after pulling (which I didn't do for quite a while). It really doesn't support implicit conversions: `Pos. This type is incompatible with string`.

**Comment by marijnh** [comment]
Understood. To continue the discussion in the other issue, adding a bunch of `toString` calls is a price I'm willing to pay, if it is a significant help towards getting static checking, but if getting there also requires more problematic changes, then I'd rather not bother.

**Comment by adrianheine** [comment]
Are you sure you are using `some`'s return value anywhere? I Just `git grep`ed `some src/` and couldn't find any place where it's not evaluated as bool.

**Comment by marijnh** [comment]
I was at one point, I may have deleted the code. I do believe the current behavior is preferable (I've often wished Array.some did the same), so now that the comment is updated, let's leave it that way.

**Comment by adrianheine** [comment]
Ok, I get that. It's probably difficult for `Array.prototype.some`, since the value for which the callback returns truthy might be any value, including a falsy one, so you would have a hard time coming up with a return value that specifies that no value matched. If people would just use `Maybe` everywhere.

**Comment by marijnh** [comment]
(Further off topic: Yeah, my proposed `Array.some` would return the value returned by the predicate, so that you could rig it to search for (truthy) values if you wanted.)

**Pull request closed without merging**
