### PR TITLE
Various inline documentation

### PR DESCRIPTION
**Pull request by ericandrewlewis**
From working on #2

### CODE REVIEW

**Comment by ericandrewlewis** [comment]
Added more docs from looking into #1

**Comment by marijnh** [comment]
Merged as 69e921d. I'm not sure yet I want to use JSDoc-style comments (since I dislike the annotation language and generating well-structured documentation pages from them is a pain), but for now they are certainly better than nothing.

**Comment by ericandrewlewis** [comment]
Why do you dislike the annotation language? Do you have a preference for other formats for code documentation? 

At the least, I think we get a generally accepted format for documenting the general qualities of structures for reading within the file. I personally have never found static parsing and documentation page generation helpful.

**Comment by marijnh** [comment]
Basically, I think the JSDoc format is very much showing its JavaDoc roots, and the notation is clunky and limited because of that. If I read through the JSDoc docs I just can't help facepalming here and there because the concepts are so wrongheaded (stuff like `@property` because, apparently, nested syntax was too hard. Or `@class`. The syntax tells you it's a class. Why add noise for that? etc)

But indeed, nothing superior seems to exist, so I guess we can go with this and maintain doc pages separately. Or maybe at some point I'll write my own script to extract documentation from the sources and put it into documentation pages in a sane way.

**Pull request closed without merging**
