### PR TITLE
Add docs for pathFromDOM()

### PR DESCRIPTION
**Pull request by ericandrewlewis**

### CODE REVIEW

**Comment by marijnh** [comment]
This isn't currently part of the public API, so it should not appear in the API docs.

**Comment by ericandrewlewis** [comment]
Ah whoops. I saw it was exported so assumed it was part of the public API. How can I tell if something is part of the public API or not?

**Comment by marijnh** [comment]
You can check whether `index.js` reexports it (for modules that have an `index.js`). For single-file modules, everything exported is public.

**Comment by marijnh** [comment]
Merged this, minus one colon, as 5b7446e

**Pull request closed without merging**
