### PR TITLE
Add documentation for inputText

### PR DESCRIPTION
**Pull request by ericandrewlewis**

### CODE REVIEW

**Comment by marijnh** [comment]
This isn't part of the public API, so it shouldn't have a doc comment, since that'll make it appear in the reference guide.

**Comment by ericandrewlewis** [comment]
Ah, gotcha. Are we interested in documenting non-public API functions?

**Comment by marijnh** [comment]
I guess, but maybe leave out the type signatures, or if you must have them, use a single colon to prevent getdocs from picking them up?

**Comment by marijnh** [comment]
Actually that's probably too obscure too (people new to the codebase will have no idea what's going on). I have to think about the proper approach some more.

**Comment by marijnh** [comment]
Well, I guess this is going to be obscure whichever way we do it. (Do you know what JSDoc projects use to control what lands in the reference docs?) I've added a CONTRIBUTING.md (e360370) mentioning this convention (single colon for non-public docs), and merged your patch as 52c6c7d92

**Pull request closed without merging**
