### PR TITLE
Draw out the instructions to run the demo

### PR DESCRIPTION
**Pull request by ericandrewlewis**
Add install notes for Node.js in case users don't have it yet, and explain each step in a bit more detail.

### CODE REVIEW

**Comment by marijnh** [comment]
The new instructions seem to assume everybody uses a Mac, though, which I don't think is an improvement (it'll confuse non-Mac users).

**Comment by ericandrewlewis** [comment]
Good point. I've removed the Mac-specific install instructions, I *think* the rest should work in any shell.

**Comment by marijnh** [comment]
`open` is still mac-specific. Also maybe mention that you have to `npm install` inside of the project's directory.

**Comment by ericandrewlewis** [comment]
Cool! Updated accordingly.

**Comment by marijnh** [comment]
Thanks. Merged as 2aaeb0f

**Pull request closed without merging**
