### PR TITLE
Add indent and unindent commands for list items

### PR DESCRIPTION
**Pull request by kiejo**
Related discussions:
Issue #92 
https://discuss.prosemirror.net/t/implementing-unindention-of-list-items/206

### CODE REVIEW

**Comment by marijnh** [comment]
Just an update: I looked into landing this, making 'indent' a separate command and folding 'dedent' into 'lift'. But this'd require quite a bit of rewriting, and I'm about to land a big API change, which would require _another_ pass over the code, so I'm going to delay this until after that's landed. Rest assured that I didn't forget about it, though.

I was thinking using Ctrl-] and Ctrl-[ as key bindings (with precedent in Google Docs and code editors), since browsers already assign an important meaning to Tab, and I don't want to trample on that by default.

**Comment by kiejo** [comment]
Thanks for the update, sounds good to me!

**Comment by marijnh** [comment]
I've added commands to the default list item (bound to Mod-[ and Mod-] by default) that roughly follow the behavior you implemented. Could you take a look?

**Comment by kiejo** [comment]
I'm happy to see these commands make it into the core library! I could find two cases that aren't being handled correctly yet:

Case 1 - Sinking a list item, wraps it in an unwanted additional list item:
li_1 Mod-] li_2

This can be fixed by placing the cursor behind the "a" and pressing Delete, which performs a join. That's also what I did here: https://github.com/ProseMirror/prosemirror/pull/261/files#diff-1b36373a78ad128adf8366680fcb47f3R329

Case 2 - Lifting a list item that has a sibling right below, wraps this sibling in an unwanted additional list item:
li_3 Mod-[ li_4

This can be fixed just like in Case 1 by placing the cursor behind "b" and pressing Delete. The code that did this is here: https://github.com/ProseMirror/prosemirror/pull/261/files#diff-1b36373a78ad128adf8366680fcb47f3R389

Apart from these two cases, I couldn't find any problems and everything seems to be working like it should.

**Comment by marijnh** [comment]
Patch 0d8371d should help with those issues.

**Pull request closed without merging**
